name: CI

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Run linter
        run: npx eslint .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Run react tests
        run: npm test -- --watchAll=false
      - name: Run cdk tests
        working-directory: ./aws-cdk
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build react app
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: app-build
          path: build
          
  deploy-cdk:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy cdk
        working-directory: ./aws-cdk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          npm install
          npm install -g aws-cdk
          cdk bootstrap '408959538248/eu-central-1'
          cdk deploy --require-approval never
    
  deploy-app:
    needs: deploy-cdk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: app-build
      - run: |
          npm install
          npm install -g aws-cdk
          aws s3 cp build s3://nexscore-app/ --recursive
