name: CI

on:
  push:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Run linter
        run: npx eslint .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npm
        run: npm install
      - name: Run tests
        run: npm test
